### ISSUE TITLE
error while installing addon

### ISSUE THREAD

**Issue by khorev001** [Quatorze14/TelekiNDOF#1]
Hi, thanx for sharing a plugin, but unfortunately it doesnt work. 

I have blender 3.4 installed and i use spacemouse wireless.

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\rk\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\TelekiNDOF-main\__init__.py", line 65, in <module>
    import spacenavigator
  File "C:\Users\rk\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\TelekiNDOF-main\..\TelekiNDOF-main\spacenavigator.py", line 2, in <module>
    import pywinusb.hid as hid
ModuleNotFoundError: No module named 'pywinusb'

**Comment by Quatorze14** [comment]
Try opening Blender in administrator mode to install the add-on. I know that some people have experience the issue where window doesn't let Blender install some dependency.

If it doesn't work after that let me know! I'll try something on my side.

Julien Roy

Julien Roy
________________________________
From: khorev001 ***@***.***>
Sent: Saturday, April 1, 2023 4:33:22 PM
To: Quatorze14/TelekiNDOF ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Quatorze14/TelekiNDOF] error while installing addon (Issue #1)


Hi, thanx for sharing a plugin, but unfortunately it doesnt work.

I have blender 3.4 installed and i use spacemouse wireless.

Traceback (most recent call last):
File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 333, in enable
mod = import(module_name)
File "C:\Users\rk\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\TelekiNDOF-main_init_.py", line 65, in
import spacenavigator
File "C:\Users\rk\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\TelekiNDOF-main..\TelekiNDOF-main\spacenavigator.py", line 2, in
import pywinusb.hid as hid
ModuleNotFoundError: No module named 'pywinusb'
